apiVersion: v1
kind: Service
metadata:
  name: reportservice
  namespace: my-prop-report
  labels:
    app: reportservice
spec:
  selector:
    app: reportservice
  ports:
    - name: http
      port: 8083
