commonLabels:
  app.kubernetes.io/genereted-by: JHipster

namespace: my-prop-report

resources:
  - namespace.yml
  # Individual apps
  - gateway-k8s/gateway-deployment.yml
  - gateway-k8s/gateway-service.yml
  - gateway-k8s/gateway-mysql.yml
  - gateway-k8s/gateway-elasticsearch.yml
  - propservice-k8s/propservice-deployment.yml
  - propservice-k8s/propservice-service.yml
  - propservice-k8s/propservice-mysql.yml
  - propservice-k8s/propservice-elasticsearch.yml
  - userservice-k8s/userservice-deployment.yml
  - userservice-k8s/userservice-service.yml
  - userservice-k8s/userservice-mysql.yml
  - userservice-k8s/userservice-elasticsearch.yml
  - reportservice-k8s/reportservice-deployment.yml
  - reportservice-k8s/reportservice-service.yml
  - reportservice-k8s/reportservice-mysql.yml
  - reportservice-k8s/reportservice-elasticsearch.yml
  - commonservice-k8s/commonservice-deployment.yml
  - commonservice-k8s/commonservice-service.yml
  - commonservice-k8s/commonservice-mysql.yml
  - commonservice-k8s/commonservice-elasticsearch.yml
  # messagebroker
  - messagebroker-k8s/kafka.yml
  # service discovery eureka/consul
  - registry-k8s/consul.yml
  - registry-k8s/consul-config-loader.yml
  - registry-k8s/application-configmap.yml

patchesJson6902:
